### ISSUE TITLE
Windows11系统下载安装包文件名的“泥融”显示为乱码

### ISSUE THREAD

**Issue by kamaslau** [Colormark/nirong#1]
版本	Windows 11 家庭中文版
版本	21H2
安装日期	‎2021/‎10/‎21
操作系统版本	22000.1696
体验	Windows 功能体验包 1000.22000.1696.0

压缩包中的.exe文件，解压前后均显示为“娉ヨ瀺_setup_1.2.8.exe”。

**Comment by Colormark** [comment]
fixed 1.2.9
