### ISSUE TITLE
Windows11系统下，标题栏所有应用级UI无响应

### ISSUE THREAD

**Issue by kamaslau** [Colormark/nirong#2]
泥融
版本1.2.8

Windows
版本 Windows 11 家庭中文版
版本 21H2
安装日期 ‎2021/‎10/‎21
操作系统版本 22000.1696
体验 Windows 功能体验包 1000.22000.1696.0

设计&预览按钮、比例调整下拉框、分享、浏览等UI均无响应，仅系统级UI（即标题栏自身）可响应鼠标右键单击事件。

**Comment by Colormark** [comment]
fixed, v1.2.10
